services:
  mysql:
    image: mysql:8.0
    container_name: ticket-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ticket_db

  redis:
    image: redis:latest
    container_name: ticket-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ticket-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"